spring:
  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://config-server.micro.local:8888

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server.micro.local:8761/eureka