server:
  port: 8082

spring:
  application:
    name: product-service

  profiles:
    active: local

  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}



#this is for AWS
#server:
#  port: 8082
#  address: 0.0.0.0
#
#spring:
#  application:
#    name: product-service
#
#  config:
#    import: "optional:configserver:"
#
#  cloud:
#    config:
#      uri: http://config-server.micro.local:8888
#
#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URL}